stages:
  - pre_check
  - auto_trans
  - build_docs
  - deploy
  - post_links

include:
  - '.gitlab/ci/build_docs.yml'
  - '.gitlab/ci/deploy.yml'
  - '.gitlab/ci/auto_trans.yml'
  - '.gitlab/ci/check_link.yml'
